env_name: kitchen-complete-v0
action_dim: 9
horizon_steps: 4
act_steps: 4
obs_dim: 60
cond_steps: 1
_target_: agent.eval.eval_shortcut_agent.EvalShortCutAgent
name: kitchen-complete-v0_eval_shortcut_mlp_ta4_td4
logdir: /home/zhangtonghe/ReinFlow-anonymous/ReinFlow/log/gym/eval/kitchen-complete-v0_eval_shortcut_mlp_ta4_td4/2025-07-30_19-08-07_42
base_policy_path: log/gym/pretrain/kitchen-complete/state_1500.pt
normalization_path: /home/zhangtonghe/ReinFlow-anonymous/ReinFlow/data/gym/kitchen-complete-v0/normalization.npz
seed: 42
device: cuda:0
sim_device: cuda:0
denoising_steps: 4
denoising_step_list:
- 4
load_ema: true
n_steps: 500
render_num: 0
env:
  n_envs: 40
  name: kitchen-complete-v0
  max_episode_steps: 280
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 4
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: /home/zhangtonghe/ReinFlow-anonymous/ReinFlow/data/gym/kitchen-complete-v0/normalization.npz
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 280
      reset_within_step: true
model:
  _target_: model.flow.shortcutflow.ShortCutFlow
  network:
    _target_: model.flow.mlp_shortcut.ShortCutFlowMLP
    horizon_steps: 4
    action_dim: 9
    cond_dim: 60
    td_emb_dim: 16
    mlp_dims:
    - 256
    - 256
    - 256
    cond_mlp_dims:
    - 32
    - 16
    activation_type: Mish
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
    embed_combination_type: add
  device: cuda:0
  horizon_steps: 4
  action_dim: 9
  act_min: -1
  act_max: 1
  obs_dim: 60
  max_denoising_steps: 4
  seed: 42
  self_consistency_k: 0.25
  delta: 1.0e-05
  sample_t_type: uniform
