######################################################################
env_name: walker2d-medium-v2
# future action forecasts
action_dim: 6
horizon_steps: 4
act_steps: 4
# observation history
obs_dim: 17
cond_steps: 1
###################################################################
# Score-based PPO Flow config
# 核心公式: ak+1 = ak + [bt(ak) + εt·st(ak)]·Δt + √(2εt·Δt)·ε
# 其中 st(x) = (t * bt(x) - x) / (1 - t) 为分数函数
###################################################################
defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.reinflow.train_ppo_flow_agent_score.TrainPPOFlowAgent
name: ${env_name}_ppo_reflow_mlp_score_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym/finetune/${env_name}_ppo_reflow_mlp_score_ta${horizon_steps}_td${denoising_steps}/${now:%Y-%m-%d}_${now:%H-%M-%S}_seed${seed}
base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/gym/pretrain/walker2d-v2/ReFlow/2025-02-06_01-39-14_D4RL/checkpoint/state_80.pt
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env_name}/normalization.npz
resume_path: null
seed: 42
device: cuda:0
sim_device: cuda:0
denoising_steps: 4
# Score-based exploration parameters
epsilon_t: 0.1
epsilon_schedule: constant
env:
  n_envs: 40
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 3
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: gym-${env_name}-finetune
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}
  offline_mode: false
train:
  n_train_itr: 1001
  n_critic_warmup_itr: 5
  n_steps: 500
  gamma: 0.99
  actor_lr: 0.0004
  actor_weight_decay: 0
  actor_lr_scheduler:
    type: cosine
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 0.0004
  critic_lr: 0.004
  critic_weight_decay: 1.0e-05
  critic_lr_scheduler:
    type: cosine
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 0.004
  save_model_freq: 300
  val_freq: 10
  render:
    freq: 1
    num: 0
  reward_scale_running: true
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 50000
  update_epochs: 5
  vf_coef: 0.5
  ent_coef: 0.03
  target_kl: 1.0
  lr_schedule: fixed
  repeat_samples: true
  verbose: false
  clip_intermediate_actions: true
  account_for_initial_stochasticity: true
model:
  _target_: model.flow.ft_ppo.ppoflow_score.PPOFlow
  device: ${device}
  policy:
    _target_: model.flow.mlp_flow_score.FlowMLP
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 16
    mlp_dims: [512,512,512]
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256,256,256]
    activation_type: Mish
    residual_style: true
  actor_policy_path: ${base_policy_path}
  act_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  cond_steps: ${cond_steps}
  inference_steps: ${denoising_steps}
  # Score-based exploration parameters
  epsilon_t: ${epsilon_t}
  epsilon_schedule: ${epsilon_schedule}
  # epsilon_min: 0.001
  # epsilon_decay_rate: 2.0
  # score_clamp_value: 10.0
  # use_score_normalization: false
  # adaptive_epsilon_lr: 0.01
  # Common parameters
  randn_clip_value: 3
  logprob_min: -1.0
  logprob_max: 1.0
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.01
  clip_ploss_coef_rate: 3
  clip_vloss_coef: null
  denoised_clip_value: 1.0
  logprob_debug_sample: false
  logprob_debug_recalculate: false