_target_: agent.eval.eval_reflow_agent.EvalReFlowAgent
name: walker2d-medium-v2_eval_reflow_mlp_ta4_td20
logdir: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/log/gym/eval/walker2d-medium-v2_eval_reflow_mlp_ta4_td20/2025-12-10_05-10-01_42
base_policy_path: ./log/gym/pretrain/walker2d-medium-v2_pre_reflow_mlp_ta4_td20_seed42/2025-12-06_03-05-56_42/checkpoint/last.pt
normalization_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/data/gym/walker2d-medium-v2/normalization.npz
seed: 42
device: cuda:0
sim_device: cuda:0
env_name: walker2d-medium-v2
obs_dim: 17
action_dim: 6
denoising_steps: 20
denoising_step_list:
- 1
- 2
- 4
cond_steps: 1
horizon_steps: 4
act_steps: 4
load_ema: true
batch_size: 128
n_steps: 500
render_num: 0
env:
  n_envs: 1
  name: walker2d-medium-v2
  max_episode_steps: 1000
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 3
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/data/gym/walker2d-medium-v2/normalization.npz
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 1000
      reset_within_step: true
model:
  _target_: model.flow.reflow.ReFlow
  network:
    _target_: model.flow.mlp_flow.FlowMLP
    horizon_steps: 4
    action_dim: 6
    cond_dim: 17
    time_dim: 16
    mlp_dims:
    - 512
    - 512
    - 512
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
  device: cuda:0
  horizon_steps: 4
  action_dim: 6
  act_min: -1
  act_max: 1
  obs_dim: 17
  max_denoising_steps: 20
  seed: 42
